#!/usr/bin/env bash
# check_qml_proto_wrappers.sh — enforce the QML→ffstream wrapper contract.
#
# Background (from aa4c816 "ffstream_client + CamerasBuiltin: add Q_INVOKABLE
# getInputsInfo wrapper for QML"):
#
# QtProtobuf auto-generates `Q_INVOKABLE void <RpcName>(const Request&, ...)`
# methods on the FFStream::Client class. From QML, calling these directly
# with a JS literal request — e.g. `ffstreamClient.GetInputsInfo({}, ...)`
# — fails: the C++ binding rejects the JS object→protobuf coercion before
# the call dispatches. The fix is the camelCase Q_INVOKABLE wrappers in
# ffstream_client.{h,cpp} that take primitive args and build the request
# in C++. Every QML caller must use those wrappers.
#
# This script greps every tracked .qml file for direct invocations of
# PascalCase RPC names against the ffstream client object and fails the
# build if any are found. PascalCase method names are derived from the
# generated `qmlffstream_client.grpc.qpb.h` so the list is automatically
# complete: any new RPC added to the proto immediately falls under the
# guard until a wrapper is provided.
#
# Usage: check_qml_proto_wrappers.sh <repo-root> [<generated-header>]
#   - repo-root:        wingout source tree.
#   - generated-header: optional path to the qml*grpc.qpb.h generated by
#                       the build. If absent, fall back to a fixed list
#                       of known wrappers (used by the headless ctest
#                       which runs after configure but before the .qpb.h
#                       files are guaranteed to exist for all paths).
#
# Exit code: 0 on pass, non-zero on first violation.
set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <repo-root> [<generated-header>]" >&2
  exit 2
fi

REPO_ROOT="$1"
HEADER_PATH="${2:-}"

if [ ! -d "$REPO_ROOT" ]; then
  echo "ERROR: repo-root does not exist: $REPO_ROOT" >&2
  exit 2
fi

# Build the list of forbidden PascalCase method names. Prefer the generated
# header if available — it's the source of truth for what the QtProtobuf
# codegen produced.
forbidden=()
if [ -n "$HEADER_PATH" ] && [ -f "$HEADER_PATH" ]; then
  while IFS= read -r name; do
    [ -n "$name" ] && forbidden+=("$name")
  done < <(
    grep -hE "Q_INVOKABLE void [A-Z][a-zA-Z0-9]+\(" "$HEADER_PATH" \
      | sed -E 's/.*Q_INVOKABLE void ([A-Z][a-zA-Z0-9]+)\(.*/\1/' \
      | sort -u
  )
fi
if [ "${#forbidden[@]}" -eq 0 ]; then
  # Fallback list — covers the RPCs that exist as of d8c7ef0/efc14e2 and
  # are wrapped in ffstream_client.h. Update when adding new wrappers.
  forbidden=(
    GetLatencies GetInputQuality GetOutputQuality GetFPSFraction GetBitRates
    GetStats InjectSubtitles AddInput RemoveInput GetInputsInfo
    SwitchOutputByProps SetOutputURL
  )
fi

# Walk every .qml file under the source tree, excluding build directories
# and vendored imports.
fail=0
while IFS= read -r -d '' qml; do
  for name in "${forbidden[@]}"; do
    # Match: ffstreamClient.<Name>( or .ffstreamClient.<Name>(. The leading
    # `\.` is critical — without it `addInput` (camelCase wrapper) would
    # match the regex for `AddInput` (PascalCase forbidden) under
    # case-insensitive matching, which would defeat the contract.
    if grep -nE "[. ]ffstreamClient\.${name}\(" "$qml" >/dev/null 2>&1; then
      echo "FORBIDDEN: $qml uses direct proto method ffstreamClient.${name}(" >&2
      grep -nE "[. ]ffstreamClient\.${name}\(" "$qml" >&2 || true
      echo "  -> use the camelCase Q_INVOKABLE wrapper from ffstream_client.h instead" >&2
      fail=1
    fi
  done
done < <(
  find "$REPO_ROOT" \
    -path "$REPO_ROOT/build*" -prune -o \
    -path "$REPO_ROOT/.build*" -prune -o \
    -path "$REPO_ROOT/import" -prune -o \
    -path "$REPO_ROOT/.git" -prune -o \
    -path "$REPO_ROOT/qt_dir" -prune -o \
    -path "$REPO_ROOT/.ccache" -prune -o \
    -name "*.qml" -type f -print0
)

if [ "$fail" -ne 0 ]; then
  echo "" >&2
  echo "Wrapper-pattern enforcement failed. Add a Q_INVOKABLE wrapper in" >&2
  echo "ffstream_client.{h,cpp} that takes primitive args and constructs" >&2
  echo "the proto request in C++; then call that camelCase wrapper from QML." >&2
  echo "Background: aa4c816 (the GetInputsInfo wrapper). Pattern: addInput," >&2
  echo "removeInput, switchOutput — all build the request in C++ from primitives." >&2
  exit 1
fi

echo "OK: no QML caller invokes a PascalCase ffstream RPC directly."
